name: 'medipreco/key-manager'
description: 'Env Var manager'
inputs:
  branch:
    description: 'The branch name to be used as key'
    required: true
    default: 'stage'
outputs:
  medenv:
    value: ${{steps.manage-key.outputs.value}}
    description: 'Key maps for the required branch in json format'
runs:
  using: 'composite'
  steps:
    - uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://med-envs/medenvs.json
        destination: ./medenvs.json
        aws_region: us-east-1
    - uses: sergeysova/jq-action@v2
      id: manage-key
      with:
        multiline: true
        cmd: export ENVTESTE='$(jq .stage.test_key medenvs.json -r)'
